export const productsData = {
  Pizzas: [
    {
      id: 1,
      name: "Margherita Pizza",
      image: "https://example.com/images/margherita_pizza.jpg",
      price: 8.99,
      description:
        "Classic pizza with fresh tomatoes, mozzarella cheese, and basil.",
    },
    {
      id: 2,
      name: "Vegetable Pizza",
      image: "https://example.com/images/vegetable_pizza.jpg",
      price: 9.49,
      description: "Topped with seasonal vegetables and mozzarella cheese.",
    },
    {
      id: 3,
      name: "Pesto Pizza",
      image: "https://example.com/images/pesto_pizza.jpg",
      price: 10.49,
      description:
        "Delicious pesto sauce with sun-dried tomatoes and mozzarella.",
    },
    {
      id: 4,
      name: "Cheese Pizza",
      image: "https://example.com/images/cheese_pizza.jpg",
      price: 7.99,
      description: "A classic cheese pizza made with rich mozzarella.",
    },
    {
      id: 5,
      name: "BBQ Vegetable Pizza",
      image: "https://example.com/images/bbq_vegetable_pizza.jpg",
      price: 10.99,
      description: "BBQ sauce topped with assorted grilled vegetables.",
    },
    {
      id: 6,
      name: "Spinach and Feta Pizza",
      image: "https://example.com/images/spinach_feta_pizza.jpg",
      price: 11.49,
      description: "Spinach and feta cheese on a tomato base.",
    },
  ],
  Burgers: [
    {
      id: "bc1",
      name: "Veggie Burger",
      image: "https://example.com/images/veggie_burger.jpg",
      price: 9.99,
      description: "A hearty burger made with black beans and quinoa.",
    },
    {
      id: "bc2",
      name: "Black Bean Burger",
      image: "https://example.com/images/black_bean_burger.jpg",
      price: 8.49,
      description: "A delicious black bean patty with spices and herbs.",
    },
    {
      id: "bc3",
      name: "Portobello Mushroom Burger",
      image: "https://example.com/images/portobello_burger.jpg",
      price: 10.49,
      description: "Grilled Portobello mushroom with fresh veggies.",
    },
    {
      id: "bc4",
      name: "Chickpea Burger",
      image: "https://example.com/images/chickpea_burger.jpg",
      price: 8.99,
      description: "A chickpea-based burger packed with flavor.",
    },
    {
      id: "bc5",
      name: "Quinoa Burger",
      image: "https://example.com/images/quinoa_burger.jpg",
      price: 9.49,
      description: "Healthy quinoa burger with fresh toppings.",
    },
    {
      id: "bc6",
      name: "Sweet Potato Burger",
      image: "https://example.com/images/sweet_potato_burger.jpg",
      price: 9.99,
      description: "Sweet potato patty with a hint of spices.",
    },
  ],
  Sandwiches: [
    {
      id: "c1",
      name: "Veggie Sandwich",
      image: "https://example.com/images/veggie_sandwich.jpg",
      price: 5.99,
      description: "Fresh vegetables with hummus on whole grain bread.",
    },
    {
      id: "c2",
      name: "Caprese Sandwich",
      image: "https://example.com/images/caprese_sandwich.jpg",
      price: 6.49,
      description: "Fresh mozzarella, tomatoes, and basil on ciabatta.",
    },
    {
      id: "c3",
      name: "Grilled Cheese Sandwich",
      image: "https://example.com/images/grilled_cheese_sandwich.jpg",
      price: 4.99,
      description: "Classic grilled cheese made with cheddar on toasted bread.",
    },
    {
      id: "c4",
      name: "Hummus and Avocado Sandwich",
      image: "https://example.com/images/hummus_avocado_sandwich.jpg",
      price: 6.99,
      description: "Creamy hummus and avocado on whole grain bread.",
    },
    {
      id: "c5",
      name: "Peanut Butter and Banana Sandwich",
      image: "https://example.com/images/peanut_butter_banana_sandwich.jpg",
      price: 5.49,
      description: "Smooth peanut butter with banana slices on bread.",
    },
    {
      id: "c6",
      name: "Egg Salad Sandwich",
      image: "https://example.com/images/egg_salad_sandwich.jpg",
      price: 5.99,
      description: "Creamy egg salad with lettuce on soft bread.",
    },
    {
      id: "c7",
      name: "Falafel Sandwich",
      image: "https://example.com/images/falafel_sandwich.jpg",
      price: 7.49,
      description: "Crispy falafel with salad and tahini sauce.",
    },
  ],
  Salads: [
    {
      id: "d1",
      name: "Caesar Salad",
      image: "https://example.com/images/caesar_salad.jpg",
      price: 7.99,
      description: "Romaine lettuce, croutons, and Caesar dressing.",
    },
    {
      id: "d2",
      name: "Greek Salad",
      image: "https://example.com/images/greek_salad.jpg",
      price: 8.49,
      description: "Tomatoes, cucumber, olives, and feta cheese.",
    },
    {
      id: "d3",
      name: "Cobb Salad",
      image: "https://example.com/images/cobb_salad.jpg",
      price: 9.49,
      description: "Mixed greens with avocado, cheese, and dressing.",
    },
    {
      id: "d4",
      name: "Quinoa Salad",
      image: "https://example.com/images/quinoa_salad.jpg",
      price: 8.99,
      description: "Nutritious quinoa mixed with fresh vegetables.",
    },
    {
      id: "d5",
      name: "Caprese Salad",
      image: "https://example.com/images/caprese_salad.jpg",
      price: 8.99,
      description:
        "Fresh mozzarella, tomatoes, and basil drizzled with balsamic.",
    },
    {
      id: "d6",
      name: "Fruit Salad",
      image: "https://example.com/images/fruit_salad.jpg",
      price: 5.99,
      description: "A mix of seasonal fruits served chilled.",
    },
    {
      id: "d7",
      name: "Spinach Salad",
      image: "https://example.com/images/spinach_salad.jpg",
      price: 7.49,
      description: "Fresh spinach with nuts and vinaigrette.",
    },
  ],
  Juices: [
    {
      id: "e1",
      name: "Orange Juice",
      image: "https://example.com/images/orange_juice.jpg",
      price: 3.49,
      description: "Freshly squeezed orange juice.",
    },
    {
      id: "e2",
      name: "Apple Juice",
      image: "https://example.com/images/apple_juice.jpg",
      price: 3.49,
      description: "Refreshing apple juice made from real apples.",
    },
    {
      id: "e3",
      name: "Carrot Juice",
      image: "https://example.com/images/carrot_juice.jpg",
      price: 3.99,
      description: "Nutritious juice made from fresh carrots.",
    },
    {
      id: "e4",
      name: "Beetroot Juice",
      image: "https://example.com/images/beetroot_juice.jpg",
      price: 4.49,
      description: "Earthy beetroot juice with a hint of lemon.",
    },
    {
      id: "e5",
      name: "Pineapple Juice",
      image: "https://example.com/images/pineapple_juice.jpg",
      price: 3.99,
      description: "Tropical pineapple juice that refreshes.",
    },
    {
      id: "e6",
      name: "Grape Juice",
      image: "https://example.com/images/grape_juice.jpg",
      price: 4.49,
      description: "Sweet and tangy grape juice.",
    },
  ],
  Smoothies: [
    {
      id: "f1",
      name: "Banana Smoothie",
      image: "https://example.com/images/banana_smoothie.jpg",
      price: 4.99,
      description: "Creamy banana smoothie with yogurt.",
    },
    {
      id: "f2",
      name: "Berry Smoothie",
      image: "https://example.com/images/berry_smoothie.jpg",
      price: 5.49,
      description: "Mixed berry smoothie with a hint of honey.",
    },
    {
      id: "f3",
      name: "Mango Smoothie",
      image: "https://example.com/images/mango_smoothie.jpg",
      price: 5.99,
      description: "Refreshing mango smoothie with coconut milk.",
    },
    {
      id: "f4",
      name: "Green Smoothie",
      image: "https://example.com/images/green_smoothie.jpg",
      price: 6.49,
      description: "Nutritious green smoothie with spinach and apple.",
    },
    {
      id: "f5",
      name: "Peanut Butter Smoothie",
      image: "https://example.com/images/peanut_butter_smoothie.jpg",
      price: 6.99,
      description: "Rich smoothie with peanut butter and bananas.",
    },
    {
      id: "f6",
      name: "Tropical Smoothie",
      image: "https://example.com/images/tropical_smoothie.jpg",
      price: 6.99,
      description: "Tropical fruits blended with yogurt.",
    },
  ],
  IceCreams: [
    {
      id: "g1",
      name: "Vanilla Ice Cream",
      image: "https://example.com/images/vanilla_ice_cream.jpg",
      price: 3.49,
      description: "Classic vanilla ice cream made with real cream.",
    },
    {
      id: "g2",
      name: "Chocolate Ice Cream",
      image: "https://example.com/images/chocolate_ice_cream.jpg",
      price: 3.99,
      description: "Rich chocolate ice cream made with premium cocoa.",
    },
    {
      id: "g3",
      name: "Strawberry Ice Cream",
      image: "https://example.com/images/strawberry_ice_cream.jpg",
      price: 4.49,
      description:
        "Delicious strawberry ice cream made from fresh strawberries.",
    },
    {
      id: "g4",
      name: "Mint Chocolate Chip Ice Cream",
      image: "https://example.com/images/mint_chocolate_chip_ice_cream.jpg",
      price: 4.99,
      description: "Refreshing mint ice cream with chocolate chips.",
    },
    {
      id: "g5",
      name: "Cookie Dough Ice Cream",
      image: "https://example.com/images/cookie_dough_ice_cream.jpg",
      price: 5.49,
      description:
        "Creamy ice cream with chunks of cookie dough and chocolate chips.",
    },
    {
      id: "g6",
      name: "Mango Sorbet",
      image: "https://example.com/images/mango_sorbet.jpg",
      price: 4.99,
      description: "Tropical mango sorbet made from real mangoes.",
    },
    {
      id: "g7",
      name: "Coffee Ice Cream",
      image: "https://example.com/images/coffee_ice_cream.jpg",
      price: 4.49,
      description: "Rich coffee-flavored ice cream made with real coffee.",
    },
  ],
};
